### ISSUE TITLE
Alignment of subreads to hifi reads

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/actc#10]
Hello

I am using the actc tool to align subreads to hifi reads and see if the subreads fills the gaps in the hifi reads. Does this alignment step take 2-3 days. It has been running for more than 1 day. The output file shows no increase in file size. Aligned.bam.tmp file size is 0 and aligned.fasta file size is 5,30539 kb. 

I used the command:

`actc m64156_221024_135809.subreads.bam m64156_221024_135809.hifi_reads.bam aligned_1.bam --chunk 10/10`

Thanks

Priya

**Comment by armintoepfer** [comment]
What gaps in HiFi are you referring to?

Do both of your input files have pbi auxillary files?

**Comment by priyambial123** [comment]
Yes, I have the pbi files for subreads and hifi reads.  I am doing this analysis as I have low number of hifi reads. I couldn't find the link where it was mentioned that CLR or subreads can used to improve structural variant detection by filling the gaps in hifi reads (which were not sequenced).

**Comment by armintoepfer** [comment]
actc is not a tool to improve any downstream analysis.

What it meant, use subreads directly in SV detection as input.

Why your process is stalling, can't help with that, as actc is a developer tool.
