### ISSUE TITLE
Query about actc chunk

### ISSUE THREAD

**Issue by ZhenyanLuo** [PacificBiosciences/actc#11]
Hi all,

I am trying to run actc with the chunk function to make 100 chunks. First 8 chunks look good like this:
9708191405 Mar 22 11:13 GM1_PL100274085-1_C01_chunk1.subreads_to_ccs.bam
9704721454 Mar 22 11:38 GM1_PL100274085-1_C01_chunk2.subreads_to_ccs.bam
9742205425 Mar 22 11:48 GM1_PL100274085-1_C01_chunk3.subreads_to_ccs.bam
9808660300 Mar 22 11:57 GM1_PL100274085-1_C01_chunk4.subreads_to_ccs.bam
...

But I got a very small chunk 9:
6956 Mar 22 12:24 GM1_PL100274085-1_C01_chunk9.subreads_to_ccs.bam
and a super large chunk 10 (even still running):
195446662538 Mar 22 14:51 GM1_PL100274085-1_C01_chunk10.subreads_to_ccs.bam.tmp
chunk 11 has a normal size again:
9904564271 Mar 22 13:33 GM1_PL100274085-1_C01_chunk11.subreads_to_ccs.bam

The command I used for making chunk 10 is: actc -j 8 GM1_PL100274085-1_C01.subreads.bam GM1_PL100274085-1_C01.ccs.bam GM1_PL100274085-1_C01_chunk10.subreads_to_ccs.bam --chunk 10/100

I was wondering whether you have any hints for this.

Thanks.

**Comment by armintoepfer** [comment]
No idea what's going on. Do you have recent .pbi files for both input BAM files?
