### ISSUE TITLE
actc version on conda

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/actc#14]
Hi, FYI - It seems that the latest actc version on conda is 0.2.0 rather than 0.5.0.
Thanks

**Comment by armintoepfer** [comment]
Thank you for the reminder.

I welcome active roles of the community for open source repos. I'm more than happy to approve the bioconda PR.

**Comment by gevro** [comment]
Ok. Not sure I did this right, but see here for PR: https://github.com/bioconda/bioconda-recipes/pull/42828
