### ISSUE TITLE
If no .bam.pbi files for associated .bam files, then actc exits without outputting stderr or stdout

### ISSUE THREAD

**Issue by jelber2** [PacificBiosciences/actc#2]
I noticed if there are no `.bam.pbi` files for associated input `.bam` files, then `actc` exits without outputting stderr or stdout (using https://github.com/PacificBiosciences/align-clr-to-ccs/releases/download/0.1.0/actc) on Debian 11 machine. A simple error message would be great as well as adding that to the documentation and how to generate the index with `pbindex` binary from bioconda package `pbbam`.

**Comment by armintoepfer** [comment]
Thanks for the bug report. I will check and fix it.

**Comment by armintoepfer** [comment]
I just checked and following checks are in place:
https://github.com/PacificBiosciences/actc/blob/main/src/main.cpp#L246-L251
https://github.com/PacificBiosciences/actc/blob/main/src/main.cpp#L292-L296
