### ISSUE TITLE
Error: ccs has multiple records. Ignoring ZMW

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/actc#22]
Hi,
I'm using the latest version of ccs (6.4.0) and actc (0.5.0).

I'm running ccs in chunks, in --by-strand mode.
Then running actc to map full subreads BAM to the ccs BAM chunk output.

I'm getting these errors from actc:
```
| 20230906 02:19:12.995 | INFO     | Fasta CCS      : Start writing CCS reads to ccs.actc.15.fasta
| 20230906 02:19:12.996 | INFO     | Fasta CCS      : 0
| 20230906 02:19:12.996 | FATAL    | CCS reader     : CCS ZMW 85132693 has multiple records. Ignoring ZMW!
| 20230906 02:19:12.996 | INFO     | Fasta CCS      : 0
| 20230906 02:19:12.996 | FATAL    | CCS reader     : CCS ZMW 85132694 has multiple records. Ignoring ZMW!
| 20230906 02:19:12.996 | INFO     | Fasta CCS      : 0
| 20230906 02:19:12.996 | FATAL    | CCS reader     : CCS ZMW 85132695 has multiple records. Ignoring ZMW!
| 20230906 02:19:12.996 | INFO     | Fasta CCS      : 0
```

Is this because the input ccs has fwd and rev reads for each ZMW? Can actc handle stranded ccs BAM?

Note, for my use case, it is critical to be able to use actc on stranded CCS BAMs.

Thanks

**Comment by armintoepfer** [comment]
The goal of `actc` has been to support training of DeepConsensus. For feature requests beyond that, I made it open source for the community to contribute back. I welcome a pull request.

**Comment by gevro** [comment]
Version 0.4.0 seems to support stranded CCS bam so I will use that for now. Thanks
