### ISSUE TITLE
perhaps excessive memory usage

### ISSUE THREAD

**Issue by flowers9** [PacificBiosciences/actc#5]
I've been running actc over some ccs -all runs (chunked into 512 parts by ccs).  16 actc threads, 12k-14k reads per chunk, and some actc jobs require more than 400gb of memory.  I can't help but wonder if there's a memory leak somewhere.

**Comment by armintoepfer** [comment]
There is no memory leak. Please update to v0.2 and try again

**Comment by flowers9** [comment]
That was version 0.2.0.

**Comment by flowers9** [comment]
Whoops, you're right, that was 0.1.0.  Thought I'd already updated, my bad.

**Comment by armintoepfer** [comment]
There are massive improvements in v0.2. Please give it a try and report back.

**Comment by flowers9** [comment]
No joke!  It now runs 100x faster (limited by our filesystem, honestly) and has a negligable memory footprint.  Output sizes appear to be the same, and I suspect I'll find the only stuff missing was nothing we cared about anyway.  Nice work.
