### ISSUE TITLE
No 'ec' flag present

### ISSUE THREAD

**Issue by ddubocan** [PacificBiosciences/actc#6]
Hi,

The output of actc no longer has the 'ec' flag.
My CCS reads contain the 'ec' flag.

code versioning:

  actc     : 0.2.0 (commit 0.2.0)
  pbbam    : 2.0.0 (commit v2.0.0-2-g0ab05eb)
  pbcopper : 2.0.0 (commit v2.0.0-2-g48411f6)
  boost    : 1.77
  htslib   : 1.14
  zlib     : 1.2.11

**Comment by ap1438** [comment]
Did the problem got solved or not.

**Comment by armintoepfer** [comment]
Feel free to send a pull request. The software is open source
