### ISSUE TITLE
Does actc take advantage of pbi to avoid reading the entire subreads.bam?

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/actc#7]
Hi Armin,

I was wondering does`actc` take advantage of pbi to avoid reading the entire subreads.bam if my ccs.bam represents only a subset of zmws? 

I was looking through the code and I think it does, but I wanted to be sure.

Thanks!
Mitchell

**Comment by mrvollger** [comment]
99.9% sure that it uses the index after some testing but going to wait for the official response to be sure.

**Comment by armintoepfer** [comment]
It does use the index.

**Comment by mrvollger** [comment]
Thanks Armin!
