### ISSUE TITLE
actc with by-strand ccs

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/actc#8]
Hi,
Can actc align subreads to a by-strand ccs BAM? Is there a way to restrict the alignment only to the CCS consensus strand sequence that matches the strand of the subread? This would be very useful for strand-specific analysis.

I imagine possible to do manually by separating the by-strand ccs BAM into two separate BAM files, one for each strand, then doing actc to each, and then removing anything aligning to the minus strand. But that seems convoluted.

Thanks.

**Comment by armintoepfer** [comment]
It's not supported and we currently don't have an use case for this
